# Generated by Django 4.2 on 2024-01-28 09:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, verbose_name='почта')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='комментарий')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_mailing_time', models.DateTimeField(auto_now=True, verbose_name='время последней рассылки')),
                ('status', models.CharField(max_length=50, null=True, verbose_name='статус попытки')),
                ('response', models.CharField(blank=True, max_length=200, null=True, verbose_name='ответ почтового сервера')),
            ],
            options={
                'verbose_name': 'log',
                'verbose_name_plural': 'logs',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название рассылки')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='время старта рассылки')),
                ('next_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='время следующей рассылки')),
                ('end_date', models.DateTimeField(verbose_name='время окончания рассылки')),
                ('interval', models.CharField(choices=[('once_a_day', 'once_a_day'), ('once_a_week', 'once_a_week'), ('once_a_month', 'once_a_month')], default='разовая', max_length=50, verbose_name='периодичность')),
                ('status', models.CharField(choices=[('start', 'start'), ('finish', 'finish'), ('created', 'created')], help_text='Выберите Создана или Завершена', max_length=50)),
                ('is_activated', models.BooleanField(default=True, verbose_name='действующая')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
                'ordering': ('start_date',),
                'permissions': [('set_is_activated', 'Может отключать рассылку')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='тема')),
                ('content', models.TextField(verbose_name='содержание')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
            },
        ),
    ]
