# Generated by Django 4.2 on 2024-01-28 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailing', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Контактный email'),
        ),
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='last_mailing_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время последней попытки'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='mailing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing', verbose_name='Рассылка'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='response',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ответ почтового сервера'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='status',
            field=models.CharField(max_length=50, null=True, verbose_name='Статус попытки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='client',
            field=models.ManyToManyField(to='mailing.client', verbose_name='Кому'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='end_date',
            field=models.DateTimeField(verbose_name='Время окончания рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='interval',
            field=models.CharField(choices=[('once_a_day', 'Один раз в день'), ('once_a_week', 'Один раз в неделю'), ('once_a_month', 'Один раз в месяц')], default='Разовая', max_length=50, verbose_name='Периодичность'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='is_activated',
            field=models.BooleanField(default=True, verbose_name='Действующая'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.message', verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='next_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время следующей рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время старта рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('start', 'Запущена'), ('finish', 'Завершена'), ('created', 'Создана')], help_text='Выберите Создана или Завершена', max_length=50),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(verbose_name='Тело письма'),
        ),
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Тема письма'),
        ),
    ]
