# Generated by Django 4.2 on 2024-01-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_alter_client_comment_alter_client_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='interval',
            field=models.CharField(choices=[('once_a_day', 'once_a_day'), ('once_a_week', 'once_a_week'), ('once_a_month', 'once_a_month')], default='Разовая', max_length=50, verbose_name='Периодичность'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('start', 'start'), ('finish', 'finish'), ('created', 'created')], help_text='Выберите Создана или Завершена', max_length=50),
        ),
    ]
